version: '3.1'
services:
  neo4j-da:
    restart: always
    image: neo4j:4.4.6
    container_name: neo4j-da
    environment:
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
      - NEO4J_dbms_connector_bolt_advertised__address=neo4j-da:7687
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_AUTH=neo4j/maya-2022
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - EXTENSION_SCRIPT=/mnt/neo4j/install_plugins.sh
    volumes:
#      - ./neo4j/data:/data
      - ./resources/neo4j:/mnt/neo4j
    ports:
      - "7474:7474"
      - "7687:7687"

  graphql-da:
    image: graphql-da:1.0
    build: .
    container_name: graphql-da
    restart: always
    environment:
      - NEO4J_SERVER=neo4j-da
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=maya-2022
    depends_on:
      - neo4j-da
    ports:
      - "4000:4000"

